spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/computerShop
    username: postgres
    password: 11111111
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    open-in-view: false